name: zyphrus
author: David Barnett
markdown: redcarpet
pygments: true
github: https://www.github.com/zyphrus
about: Hello! I am a student at Victoria University in New Zealand studying software engineering

urls:
    - text: github
      url: https://github.com/zyphrus
    - text: email
      url: mailto:david@barnett.net.nz

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
