title: zyphrus
email: david@barnett.net.nz
description: | # this means to ignore newlines until "baseurl:"
  David Barnett, a student of software engineer living in New Zealand.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zyphrus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sysvii
github_username:  zyphrus
disqus:
    shortname: zyphrus-swen

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
